[package]
name = "web-bundler"
description = "Bundles a Seed SPA for publishing"
version = "0.1.0"
edition = "2018"

[dependencies]
fs_extra = "1.2"
sass-rs = "0.2"
anyhow = "1"
tera = "1.5.0"
walkdir = "2.3.1"
rand = "0.7.3"